// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsXVzaAau-fal9ORWGnh57Wo5hy9t2yho',
    appId: '1:163490489798:web:4bd55b393b51ab8d95bec7',
    messagingSenderId: '163490489798',
    projectId: 'roadsos-5baa1',
    authDomain: 'roadsos-5baa1.firebaseapp.com',
    storageBucket: 'roadsos-5baa1.firebasestorage.app',
    measurementId: 'G-CZ9F42BD0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRhn4-wJI86kmU1nCiYUlU_i6kbiLEzmI',
    appId: '1:163490489798:android:3f48be45779da04295bec7',
    messagingSenderId: '163490489798',
    projectId: 'roadsos-5baa1',
    storageBucket: 'roadsos-5baa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJcKCDyeHz4p8mplVshw7pjHWUHd8HQ4',
    appId: '1:163490489798:ios:44a81097238915c895bec7',
    messagingSenderId: '163490489798',
    projectId: 'roadsos-5baa1',
    storageBucket: 'roadsos-5baa1.firebasestorage.app',
    iosBundleId: 'com.example.roadsos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJcKCDyeHz4p8mplVshw7pjHWUHd8HQ4',
    appId: '1:163490489798:ios:44a81097238915c895bec7',
    messagingSenderId: '163490489798',
    projectId: 'roadsos-5baa1',
    storageBucket: 'roadsos-5baa1.firebasestorage.app',
    iosBundleId: 'com.example.roadsos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsXVzaAau-fal9ORWGnh57Wo5hy9t2yho',
    appId: '1:163490489798:web:84cae2fc60dd85e995bec7',
    messagingSenderId: '163490489798',
    projectId: 'roadsos-5baa1',
    authDomain: 'roadsos-5baa1.firebaseapp.com',
    storageBucket: 'roadsos-5baa1.firebasestorage.app',
    measurementId: 'G-ZR3K96BXYR',
  );
}
